-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

SET check_function_bodies = false;

DROP EXTENSION pg_net;

CREATE ROLE supabase_privileged_role;

GRANT supabase_privileged_role TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;

CREATE FUNCTION public.get_sync_count (
  target_user_id uuid
)
  RETURNS integer
  LANGUAGE sql
  SECURITY DEFINER
  AS $function$
  select count(*)
  from follows f1
  where f1.follower_id = target_user_id  -- 1. I follow them
  and f1.is_approved = true              -- (Approved)
  and exists (
    select 1 from follows f2
    where f2.follower_id = f1.following_id -- 2. AND they follow me back
    and f2.following_id = target_user_id
    and f2.is_approved = true            -- (Approved)
  );
$function$;

GRANT ALL ON FUNCTION public.get_sync_count(uuid) TO anon;

GRANT ALL ON FUNCTION public.get_sync_count(uuid) TO authenticated;

GRANT ALL ON FUNCTION public.get_sync_count(uuid) TO service_role;

CREATE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$
begin
  insert into public.profiles (id, username, bio, avatar_url)
  values (
    new.id, 
    new.raw_user_meta_data->>'username',
    '', 
    ''
  );
  return new;
end;
$function$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

GRANT ALL ON FUNCTION public.handle_new_user() TO anon;

GRANT ALL ON FUNCTION public.handle_new_user() TO authenticated;

GRANT ALL ON FUNCTION public.handle_new_user() TO service_role;

CREATE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

GRANT ALL ON FUNCTION public.rls_auto_enable() TO anon;

GRANT ALL ON FUNCTION public.rls_auto_enable() TO authenticated;

GRANT ALL ON FUNCTION public.rls_auto_enable() TO service_role;

CREATE TABLE public.artist_follows (
  id                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id           uuid                     NOT NULL,
  spotify_artist_id text                     NOT NULL,
  artist_name       text                     NOT NULL,
  artist_image_url  text,
  created_at        timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  genres            text[]                   DEFAULT '{}'::text[]
);

ALTER TABLE public.artist_follows
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.artist_follows
  ADD CONSTRAINT artist_follows_pkey PRIMARY KEY (id);

ALTER TABLE public.artist_follows
  ADD CONSTRAINT artist_follows_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.artist_follows
  ADD CONSTRAINT artist_follows_user_id_spotify_artist_id_key UNIQUE (user_id, spotify_artist_id);

GRANT ALL ON public.artist_follows TO anon;

GRANT ALL ON public.artist_follows TO authenticated;

GRANT ALL ON public.artist_follows TO service_role;

CREATE INDEX idx_artist_follows_spotify_id ON public.artist_follows (spotify_artist_id);

CREATE POLICY "Public rotations are viewable" ON public.artist_follows
  FOR SELECT
  USING (true);

CREATE POLICY "Users can add to rotation" ON public.artist_follows
  FOR INSERT
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can remove from rotation" ON public.artist_follows
  FOR DELETE
  USING ((auth.uid() = user_id));

CREATE TABLE public.comments (
  id         uuid                     DEFAULT gen_random_uuid() NOT NULL,
  post_id    uuid                     NOT NULL,
  user_id    uuid,
  parent_id  uuid,
  content    text                     NOT NULL,
  is_voided  boolean                  DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.comments
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.comments
  ADD CONSTRAINT comments_content_check CHECK (char_length(content) <= 10000);

ALTER TABLE public.comments
  ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

ALTER TABLE public.comments
  ADD CONSTRAINT comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE CASCADE;

GRANT ALL ON public.comments TO anon;

GRANT ALL ON public.comments TO authenticated;

GRANT ALL ON public.comments TO service_role;

CREATE INDEX idx_comments_post_id ON public.comments (post_id);

CREATE POLICY comments_delete ON public.comments
  FOR DELETE
  USING ((auth.uid() = user_id));

CREATE POLICY comments_insert ON public.comments
  FOR INSERT
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY comments_select ON public.comments
  FOR SELECT
  USING (true);

CREATE POLICY comments_update ON public.comments
  FOR UPDATE
  USING ((auth.uid() = user_id));

CREATE TABLE public.follows (
  follower_id  uuid                     NOT NULL,
  following_id uuid                     NOT NULL,
  created_at   timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  is_approved  boolean                  DEFAULT true,
  status       text                     DEFAULT 'accepted'::text NOT NULL
);

ALTER TABLE public.follows
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.follows
  ADD CONSTRAINT follows_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.follows
  ADD CONSTRAINT follows_following_id_fkey FOREIGN KEY (following_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.follows
  ADD CONSTRAINT follows_pkey PRIMARY KEY (follower_id, following_id);

ALTER TABLE public.follows
  ADD CONSTRAINT prevent_self_follow CHECK (follower_id <> following_id);

GRANT ALL ON public.follows TO anon;

GRANT ALL ON public.follows TO authenticated;

GRANT ALL ON public.follows TO service_role;

CREATE POLICY "Public follows are viewable" ON public.follows
  FOR SELECT
  USING (true);

CREATE POLICY "Users can create follows" ON public.follows
  FOR INSERT
  WITH CHECK ((auth.uid() = follower_id));

CREATE POLICY "Users can decline their own incoming requests" ON public.follows
  FOR DELETE
  TO authenticated
  USING ((auth.uid() = following_id));

CREATE POLICY "Users can delete follows" ON public.follows
  FOR DELETE
  USING ((auth.uid() = follower_id));

CREATE TABLE public.posts (
  id         uuid                     DEFAULT gen_random_uuid() NOT NULL,
  wall_id    uuid                     NOT NULL,
  user_id    uuid,
  title      text                     NOT NULL,
  content    text                     NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.posts
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.posts
  ADD CONSTRAINT posts_content_check CHECK (char_length(content) <= 40000);

ALTER TABLE public.posts
  ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

ALTER TABLE public.comments
  ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE public.posts
  ADD CONSTRAINT posts_title_check CHECK (char_length(title) <= 300);

GRANT ALL ON public.posts TO anon;

GRANT ALL ON public.posts TO authenticated;

GRANT ALL ON public.posts TO service_role;

CREATE INDEX idx_posts_wall_id ON public.posts (wall_id);

CREATE POLICY posts_delete ON public.posts
  FOR DELETE
  USING ((auth.uid() = user_id));

CREATE POLICY posts_insert ON public.posts
  FOR INSERT
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY posts_select ON public.posts
  FOR SELECT
  USING (true);

CREATE TABLE public.profiles (
  id                     uuid                     NOT NULL,
  username               text,
  bio                    text                     DEFAULT ''::text,
  avatar_url             text                     DEFAULT ''::text,
  created_at             timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  is_private             boolean                  DEFAULT false NOT NULL,
  spotify_url            text,
  show_currently_playing boolean                  DEFAULT true,
  spotify_id             text,
  show_top_artists       boolean                  DEFAULT true,
  show_playlists         boolean                  DEFAULT true
);

ALTER TABLE public.profiles
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);

ALTER TABLE public.comments
  ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.posts
  ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_username_key UNIQUE (username);

GRANT ALL ON public.profiles TO anon;

GRANT ALL ON public.profiles TO authenticated;

GRANT ALL ON public.profiles TO service_role;

CREATE INDEX idx_profiles_spotify_id ON public.profiles (spotify_id);

CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT
  USING (true);

CREATE POLICY "Users can only update their own profile" ON public.profiles
  FOR UPDATE
  TO authenticated
  USING ((auth.uid() = id))
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE
  USING ((auth.uid() = id));

CREATE POLICY "Users can update their own profiles" ON public.profiles
  FOR UPDATE
  TO authenticated
  USING ((auth.uid() = id))
  WITH CHECK ((auth.uid() = id));

CREATE TABLE public.published_playlists (
  id                  uuid                     DEFAULT extensions.uuid_generate_v4() NOT NULL,
  user_id             uuid                     NOT NULL,
  spotify_playlist_id text                     NOT NULL,
  name                text                     NOT NULL,
  image_url           text,
  tracks_total        integer                  DEFAULT 0,
  created_at          timestamp with time zone DEFAULT now()
);

ALTER TABLE public.published_playlists
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.published_playlists
  ADD CONSTRAINT published_playlists_pkey PRIMARY KEY (id);

ALTER TABLE public.published_playlists
  ADD CONSTRAINT published_playlists_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.published_playlists
  ADD CONSTRAINT published_playlists_user_id_spotify_playlist_id_key UNIQUE (user_id, spotify_playlist_id);

GRANT ALL ON public.published_playlists TO anon;

GRANT ALL ON public.published_playlists TO authenticated;

GRANT ALL ON public.published_playlists TO service_role;

CREATE POLICY "Public profiles can view published playlists" ON public.published_playlists
  FOR SELECT
  USING (true);

CREATE POLICY "Users can manage their own published playlists" ON public.published_playlists
  USING ((auth.uid() = user_id));

CREATE TABLE public.reviews (
  id              uuid                     DEFAULT gen_random_uuid() NOT NULL,
  user_id         uuid                     NOT NULL,
  album_id        text                     NOT NULL,
  rating          integer,
  content         text,
  album_name      text                     NOT NULL,
  artist_name     text                     NOT NULL,
  album_image_url text                     NOT NULL,
  created_at      timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at      timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reviews
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.reviews
  ADD CONSTRAINT must_have_data CHECK (rating IS NOT NULL OR content IS NOT NULL);

ALTER TABLE public.reviews
  ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);

ALTER TABLE public.reviews
  ADD CONSTRAINT reviews_rating_check CHECK (rating >= 0 AND rating <= 100);

ALTER TABLE public.reviews
  ADD CONSTRAINT reviews_user_id_album_id_key UNIQUE (user_id, album_id);

ALTER TABLE public.reviews
  ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

GRANT ALL ON public.reviews TO anon;

GRANT ALL ON public.reviews TO authenticated;

GRANT ALL ON public.reviews TO service_role;

CREATE POLICY "Reviews are viewable by everyone." ON public.reviews
  FOR SELECT
  USING (true);

CREATE POLICY "Users can create reviews." ON public.reviews
  FOR INSERT
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can delete own reviews." ON public.reviews
  FOR DELETE
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update own reviews." ON public.reviews
  FOR UPDATE
  USING ((auth.uid() = user_id));

CREATE TABLE public.spotify_signals (
  user_id     uuid                     NOT NULL,
  track_name  text,
  artist_name text,
  is_playing  boolean                  DEFAULT true,
  updated_at  timestamp with time zone DEFAULT now()
);

ALTER TABLE public.spotify_signals
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.spotify_signals
  ADD CONSTRAINT spotify_signals_pkey PRIMARY KEY (user_id);

ALTER TABLE public.spotify_signals
  ADD CONSTRAINT spotify_signals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

GRANT ALL ON public.spotify_signals TO anon;

GRANT ALL ON public.spotify_signals TO authenticated;

GRANT ALL ON public.spotify_signals TO service_role;

CREATE POLICY "Authenticated users can read signals" ON public.spotify_signals
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Users can manage their own signal" ON public.spotify_signals
  TO authenticated
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE TABLE public.spotify_top_artists (
  user_id    uuid                     NOT NULL,
  artists    jsonb                    DEFAULT '[]'::jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.spotify_top_artists
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.spotify_top_artists
  ADD CONSTRAINT spotify_top_artists_pkey PRIMARY KEY (user_id);

ALTER TABLE public.spotify_top_artists
  ADD CONSTRAINT spotify_top_artists_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

GRANT ALL ON public.spotify_top_artists TO anon;

GRANT ALL ON public.spotify_top_artists TO authenticated;

GRANT ALL ON public.spotify_top_artists TO service_role;

CREATE POLICY "Anyone can view top artists" ON public.spotify_top_artists
  FOR SELECT
  USING (true);

CREATE POLICY "Users manage own top artists" ON public.spotify_top_artists
  USING ((auth.uid() = user_id));

CREATE TABLE public.votes (
  id         uuid                     DEFAULT gen_random_uuid() NOT NULL,
  user_id    uuid                     NOT NULL,
  post_id    uuid,
  comment_id uuid,
  vote_type  smallint                 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.votes
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.votes
  ADD CONSTRAINT votes_check CHECK (post_id IS NOT NULL AND comment_id IS NULL OR post_id IS NULL AND comment_id IS NOT NULL);

ALTER TABLE public.votes
  ADD CONSTRAINT votes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id) ON DELETE CASCADE;

ALTER TABLE public.votes
  ADD CONSTRAINT votes_pkey PRIMARY KEY (id);

ALTER TABLE public.votes
  ADD CONSTRAINT votes_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE public.votes
  ADD CONSTRAINT votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE public.votes
  ADD CONSTRAINT votes_vote_type_check CHECK (vote_type = ANY (ARRAY[1, '-1'::integer]));

GRANT ALL ON public.votes TO anon;

GRANT ALL ON public.votes TO authenticated;

GRANT ALL ON public.votes TO service_role;

CREATE INDEX idx_votes_post_id ON public.votes (post_id)
  WHERE post_id IS NOT NULL;

CREATE UNIQUE INDEX idx_unique_vote_comment ON public.votes (user_id, comment_id)
  WHERE comment_id IS NOT NULL;

CREATE UNIQUE INDEX idx_unique_vote_post ON public.votes (user_id, post_id)
  WHERE post_id IS NOT NULL;

CREATE INDEX idx_votes_comment_id ON public.votes (comment_id)
  WHERE comment_id IS NOT NULL;

CREATE POLICY votes_delete ON public.votes
  FOR DELETE
  USING ((auth.uid() = user_id));

CREATE POLICY votes_insert ON public.votes
  FOR INSERT
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY votes_select ON public.votes
  FOR SELECT
  USING (true);

CREATE TABLE public.walls (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  spotify_artist_id text                     NOT NULL,
  created_at        timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.walls
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.walls
  ADD CONSTRAINT walls_pkey PRIMARY KEY (id);

ALTER TABLE public.posts
  ADD CONSTRAINT posts_wall_id_fkey FOREIGN KEY (wall_id) REFERENCES public.walls(id) ON DELETE CASCADE;

ALTER TABLE public.walls
  ADD CONSTRAINT walls_spotify_artist_id_key UNIQUE (spotify_artist_id);

GRANT ALL ON public.walls TO anon;

GRANT ALL ON public.walls TO authenticated;

GRANT ALL ON public.walls TO service_role;

CREATE POLICY walls_insert ON public.walls
  FOR INSERT
  WITH CHECK ((auth.uid() IS NOT NULL));

CREATE POLICY walls_select ON public.walls
  FOR SELECT
  USING (true);

CREATE EVENT TRIGGER ensure_rls
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION public.rls_auto_enable();
